### PR TITLE
change the operational character

### PR DESCRIPTION
**Pull request by hdoer**
In order to compute faster.

### CODE REVIEW

**Review by khituras — APPROVED** [review]
Good catch, the point of this condition is to use the smaller set, instead it always uses the larger.

**Comment by khituras** [comment]
Did you report this to the original lingpipe people as well?

**Comment by hdoer** [comment]
No, I did't. I don't know who is "original lingpipe people".

**Comment by khituras** [comment]
I see. Please note that the original software stems from the Alias-I corporation, this is the official lingpipe home page: http://alias-i.com/lingpipe/index.html

**Pull request merged**
